#Modify all lines indicated with MODIFY
query:
  plink: "PATH_TO_PLINK_PREFIX" #MODIFY: Prefix for PLINK files to be used as initial input for GWAS using hard genotype call
  dosage_vcf: "none" #Optional path to a VCF (gzipped is fine) file containing dosage data. Set to 'none' if not available.
samples: "all"  # This can be set to path of file containing individuals to be kept from merged query file. One sample per line.
sites: "all" # This can be set to path of file containing SNPs to be EXCLUDED from merged query file. One SNP ID per line.
outname: "CCRLP" # MODIFY: prefix used for naming output
admixMapping:
  skip: 'false'  #Set to true if admixture mapping should be skipped. E.g. if RFMix has not been run for this dataset
  rfmix: "OUTPUT_DIRECTORY_OF RFMIX" #MODIFY if skip is set to false.
  gen_since_admixture: '8' #Set as same value used in RFMix.  Used here for determining significance threshold
  cores: '12'
  ancestry_predictors: 'AFR,EUR,AMR' #Comma, separated list (no spaces) indicating the ancestry components that should be tested for an effect.
  other_predictors: 'sex'  # this should include the variable names provided in covariate_file if those variables are desired to be included in the admixture mapping.
  sig_threshold: '0.005' # Used for annotation purposes.  Windows with p-value below this will be annotated with overlapping genes
  annotation_buffer: '100000' #Add this amount to each side of the window when looking for overlapping genes.
gwas:
  mbc_pval: '0.0001' # pvalue threshold for missingness-by-case
  missingness: '0.05' # missingness threshold
  maf: '0.01' # Minor allele frequency threshold
  pc_num: '4' # Number of PCs to use in GWAS
  blink_dir: "/usr/local/bin/BLINK" # Do not change. Deprecated
  cores: '12'
  sig_threshold: '0.000005' # Used for annotation.  SNPs with p-value below this will be annotated via SNPEff
  other_predictors: 'sex'  # this should include the variable names provided in covariate_file if those variables are desired to be included in the admixture mapping.
singularity:
  use_singularity: 'true' #Use a singularity image (i.e. set to true) if possible.  Pipeline has only been tested/debugged with singularity.
  image: '/home/araduski/shared/singularity/AncestryInference.sif' # MODIFY: Path to singularity image file.  The one I used for everything is named AncestryInference.sif, which can be created from scratch using .def file in repo.
  code: 'scripts/' #Path to the scripts directory that was cloned with repo.  Should not need to change this value.
  module: 'module load singularity' #Command that the HPC requires for use of singularity.  Set to empty string if singularity is loaded by default.
LD_pruning:
  window_size: "50" #See plink documentation for LD pruning to understanding what these parameters mean
  step_size: "5"
  r2_threshold: "0.3" #Remove 1 SNP from a pair in which squared correlation exceeds this value
sHWE:
  pop_nums: '1,2,3,4,5,6' # From these choices, the pipeline will try to find the optimal number of populations to use in latent factor analysis used in the structured HWE procedure.  The program will error out as values increase (e.g. 8 for ADMIRAL).
  threshold: '0.000001' # p-value threshold for filtering based on departure from sHWE
  bins: '30' #Used for identifying optimal value for population number.  Number of bins to divide p-value distribution into.  Sensitivity to this parameter has not been tested.
  downsample_rounds: '2000' # Number of downsampled (DS) datasets to create. See the README for discussion on why this is necessary
  downsample_number: '1000' # Number of individuals in each DS dataset
  maf: '0.05' # Markers with minor allele frequency below this will be removed
  test_threshold: '500000' # Number of markers to be tested.  Only markers that pass sHWE test will be used for structure & kinship estimation.  It can take a lot of rounds of downsampling to achieve high numbers here, so reduce this value if not passing checkpoints. 200k is sufficient.
IBD:
  maf: '0.05' # Markers with minor allele frequency below this will be removed
  cpj: '100000' # number of comparisons per job for IBS calculation
  pi_hat: '0.1875' # 0.1875 is suggested by doi: 10.1038/nprot.2010.116.
  filter_relateds: 'false' # This should be left as false.  No need to filter related individuals in BLINK or GENESIS.  However, this is enforced in admixture mapping regardless of value set here.
kinship_threshold: '0.125'  # Values below this are set to 0 (unrelated) in GENESIS
match_controls: 'false' #If set to true, data will be subset to matched controls via PLINK's clustering based control matching algorithm.
control_number: '4' #Ignored if match_controls is set to false.  Otherwise, this many controls will be retained for each case sample.
covariate_file: 'none' # Not tested; Tab-delimited file with header line specifying names of covariates.  First column MUST be labeled with 'taxa' and should contain sample IDs EXACTLY as they are specified in input plink files.
cmd_prefix: "module load plink/1.90b6.10; module load htslib/1.6; module load bcftools/1.9;"
run_settings:
  local_run: 'false'
  cluster_config: 'workflow/cluster_slurm.yaml'
  scheduler: 'slurm'
annotation:
  rsIDs: "/home/spectorl/pmonnaha/misc/hg19_rsID_key.txt"
  download_refs: 'true'
  gff: 'ftp://ftp.ensembl.org/pub/grch37/current/gff3/homo_sapiens/Homo_sapiens.GRCh37.87.gff3.gz'
  genome: ''
  typed_key: 'none'
conditional_analysis:
    snp_list: 'none' # One column with snpIDs
    distance: '100' # in kb!!!
fine_mapping:
    snp_list: 'none'
    distance: '100' #in kb!!!
